name: "Blue/Green Beanstalk"
description: "GitHub Action that automates deployment to AWS Elastic Beanstalk Blue/Green environments."
inputs:
  app_name:
    description: "Name of the Elastic Beanstalk application. If it doesn't exist, it will be created."
    required: true
  aws_access_key_id:
    description: "AWS Access Key ID. May instead be specified via the AWS_ACCESS_KEY_ID environment variable."
    required: true
  aws_region:
    description: "AWS region. May instead be specified via the AWS_REGION environment variable."
    required: false
  aws_secret_access_key:
    description: "AWS Secret Access Key. May instead be specified via the AWS_SECRET_ACCESS_KEY environment variable."
    required: false
  aws_session_token:
    description: "AWS session token to use when using temporary credentials. May instead be specified via the AWS_SESSION_TOKEN environment variable."
    required: false
  blue_env:
    description: "Name of the Blue environment"
    required: true
  deploy:
    description: "Whether to deploy the new application version to the target environment"
    required: true
    default: true
  green_env:
    description: "Name of the Green environment"
    required: true
  platform_branch_name:
    description: "Name of the platform branch to use. When creating a new environment, it will be launched with the latest version of the specified platform branch. To see the list of available platform branches, run the `aws elasticbeanstalk list-platform-branches` command."
    required: true
  production_cname:
    description: "CNAME prefix for the production environment"
    required: true
  staging_cname:
    description: "CNAME prefix for the staging environment"
    required: true
  swap_cnames:
    description: "Whether to swap the CNAMEs of the staging and production environments"
    required: true
    default: true
  template_name:
    description: "Name of an Elastic Beanstalk configuration template to use when creating a new environment. If no template is specified, default option settings will be used."
    required: false
  wait_for_create_env:
    description: "Whether to wait for the target environment to become healthy after creation. If set to false, the action will terminate immediately after starting the createEnvironment process."
    required: true
    default: true
outputs:
  target_env:
    description: "Name of the target environment, to which the new application version should be deployed"
runs:
  using: "node20"
  main: "dist/index.js"
