name: "Blue/Green Beanstalk"
description: "GitHub Action that automates deployment to AWS Elastic Beanstalk Blue/Green environments. If the staging environment is not healthy, the action will terminate and recreate it with the given template."
inputs:
  app_name:
    description: "Name of the Elastic Beanstalk application"
    required: true
  aws_access_key_id:
    description: "AWS Access Key ID"
    required: true
  aws_secret_access_key:
    description: "AWS Secret Access Key"
    required: true
  blue_env:
    description: "Name of the Blue environment"
    required: true
  deploy:
    description: "Whether to deploy the new application version to the target environment"
    required: true
  green_env:
    description: "Name of the Green environment"
    required: true
  region:
    description: "AWS region"
    required: true
  production_cname:
    description: "CNAME prefix of the production environment"
    required: true
  staging_cname:
    description: "CNAME prefix of the staging environment"
    required: true
  swap_cnames:
    description: "Whether to swap the CNAMEs of the staging and production environments"
    required: true
  template_name:
    description: "Name of the Elastic Beanstalk template"
    required: true
  wait_for_create_env:
    description: "Whether to wait for the target environment to become healthy"
    required: true
outputs:
  target_env:
    description: "Name of the target environment, to which the new application version should be deployed"
runs:
  using: "node20"
  main: "dist/index.js"
